package org.tsn.entity;

// Generated Apr 23, 2015 9:21:54 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TCauses generated by hbm2java
 */
@Entity
@Table(name = "t_causes", catalog = "tsn_test")
public class TCauses implements IBaseEntity
{

	private Integer			causeId;
	private String			causeDescr;
	private String			TCausescol;
	private String			TCausescol1;
	private Set<TProjects>	TProjectses	= new HashSet<TProjects>(0);

	public TCauses()
	{
	}

	public TCauses(
		String causeDescr,
		String TCausescol,
		String TCausescol1,
		Set<TProjects> TProjectses)
	{
		this.causeDescr = causeDescr;
		this.TCausescol = TCausescol;
		this.TCausescol1 = TCausescol1;
		this.TProjectses = TProjectses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CAUSE_ID", unique = true, nullable = false)
	public Integer getCauseId()
	{
		return this.causeId;
	}

	public void setCauseId(Integer causeId)
	{
		this.causeId = causeId;
	}

	@Column(name = "CAUSE_DESCR", length = 100)
	public String getCauseDescr()
	{
		return this.causeDescr;
	}

	public void setCauseDescr(String causeDescr)
	{
		this.causeDescr = causeDescr;
	}

	@Column(name = "t_causescol", length = 45)
	public String getTCausescol()
	{
		return this.TCausescol;
	}

	public void setTCausescol(String TCausescol)
	{
		this.TCausescol = TCausescol;
	}

	@Column(name = "t_causescol1", length = 45)
	public String getTCausescol1()
	{
		return this.TCausescol1;
	}

	public void setTCausescol1(String TCausescol1)
	{
		this.TCausescol1 = TCausescol1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCauses")
	public Set<TProjects> getTProjectses()
	{
		return this.TProjectses;
	}

	public void setTProjectses(Set<TProjects> TProjectses)
	{
		this.TProjectses = TProjectses;
	}

}
