package org.tsn.entity;

// Generated Mar 11, 2015 11:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCauses generated by hbm2java
 */
@Entity
@Table(name = "t_causes")
public class TCauses implements IBaseEntity 
{

	private static final long serialVersionUID = 340275821748786899L;
	private Integer causeId;
	private String causeDescr;

	public TCauses() {
	}

	public TCauses(String causeDescr) {
		this.causeDescr = causeDescr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CAUSE_ID", unique = true, nullable = false)
	public Integer getCauseId() {
		return this.causeId;
	}

	public void setCauseId(Integer causeId) {
		this.causeId = causeId;
	}

	@Column(name = "CAUSE_DESCR", length = 100)
	public String getCauseDescr() {
		return this.causeDescr;
	}

	public void setCauseDescr(String causeDescr) {
		this.causeDescr = causeDescr;
	}

}
