package org.tsn.entity;

// Generated Feb 19, 2015 10:13:35 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TLogin generated by hbm2java
 */
@Entity
@Table(name = "t_login", uniqueConstraints = @UniqueConstraint(columnNames = "USER_NAME"))
public class TLogin implements IBaseEntity {

	private static final long serialVersionUID = 254648341771097543L;
	
	private Integer loginId;
	private String userName;
	private String password;
	private Set<TProfile> TProfiles = new HashSet<TProfile>(0);

	public TLogin() {
	}

	public TLogin(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public TLogin(String userName, String password, Set<TProfile> TProfiles) {
		this.userName = userName;
		this.password = password;
		this.TProfiles = TProfiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOGIN_ID", unique = true, nullable = false)
	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	@Column(name = "USER_NAME", unique = true, nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TLogin")
	public Set<TProfile> getTProfiles() {
		return this.TProfiles;
	}

	public void setTProfiles(Set<TProfile> TProfiles) {
		this.TProfiles = TProfiles;
	}

}
