package org.tsn.entity;

// Generated Jul 23, 2015 8:29:33 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TProjectType generated by hbm2java
 */
@Entity
@Table(name = "t_project_type", catalog = "tsn_test")
public class TProjectType implements IBaseEntity
{

	private int				projectTypeId;
	private String			typeDescr;
	private Set<TProject>	TProjectses	= new HashSet<TProject>(0);

	public TProjectType()
	{
	}

	public TProjectType(int projectTypeId)
	{
		this.projectTypeId = projectTypeId;
	}

	public TProjectType(
		int projectTypeId,
		String typeDescr,
		Set<TProject> TProjectses)
	{
		this.projectTypeId = projectTypeId;
		this.typeDescr = typeDescr;
		this.TProjectses = TProjectses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_type_id", unique = true, nullable = false)
	public int getProjectTypeId()
	{
		return this.projectTypeId;
	}

	public void setProjectTypeId(int projectTypeId)
	{
		this.projectTypeId = projectTypeId;
	}

	@Column(name = "type_descr", length = 100)
	public String getTypeDescr()
	{
		return this.typeDescr;
	}

	public void setTypeDescr(String typeDescr)
	{
		this.typeDescr = typeDescr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProjectType")
	public Set<TProject> getTProjectses()
	{
		return this.TProjectses;
	}

	public void setTProjectses(Set<TProject> TProjectses)
	{
		this.TProjectses = TProjectses;
	}

}
