package org.tsn.entity;

// Generated Feb 19, 2015 10:13:35 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TSecurityQuestions generated by hbm2java
 */
@Entity
@Table(name = "t_security_questions" )
public class TSecurityQuestions implements IBaseEntity {

	private static final long serialVersionUID = -7370938442888206720L;

	private Integer questionId;
	private String questionText;
	private Set<TSecurityAnswers> TSecurityAnswerses = new HashSet<TSecurityAnswers>(
			0);

	public TSecurityQuestions() {
	}

	public TSecurityQuestions(String questionText) {
		this.questionText = questionText;
	}

	public TSecurityQuestions(String questionText,
			Set<TSecurityAnswers> TSecurityAnswerses) {
		this.questionText = questionText;
		this.TSecurityAnswerses = TSecurityAnswerses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUESTION_ID", unique = true, nullable = false)
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@Column(name = "QUESTION_TEXT", nullable = false, length = 50)
	public String getQuestionText() {
		return this.questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TSecurityQuestions")
	public Set<TSecurityAnswers> getTSecurityAnswerses() {
		return this.TSecurityAnswerses;
	}

	public void setTSecurityAnswerses(Set<TSecurityAnswers> TSecurityAnswerses) {
		this.TSecurityAnswerses = TSecurityAnswerses;
	}

}
