package org.tsn.entity;

// Generated Feb 19, 2015 10:13:35 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TSecurityAnswers generated by hbm2java
 */
@Entity
@Table(name = "t_security_answers")
public class TSecurityAnswers implements IBaseEntity{

	private static final long serialVersionUID = -3973043274382560493L;

	private int securityAnswerId;
	private TSecurityQuestions TSecurityQuestions;
	private TProfile TProfile;
	private String answerDescr;

	public TSecurityAnswers() {
	}

	public TSecurityAnswers(int securityAnswerId) {
		this.securityAnswerId = securityAnswerId;
	}

	public TSecurityAnswers(int securityAnswerId,
			TSecurityQuestions TSecurityQuestions, TProfile TProfile,
			String answerDescr) {
		this.securityAnswerId = securityAnswerId;
		this.TSecurityQuestions = TSecurityQuestions;
		this.TProfile = TProfile;
		this.answerDescr = answerDescr;
	}

	@Id
	@Column(name = "SECURITY_ANSWER_ID", unique = true, nullable = false)
	public int getSecurityAnswerId() {
		return this.securityAnswerId;
	}

	public void setSecurityAnswerId(int securityAnswerId) {
		this.securityAnswerId = securityAnswerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID")
	public TSecurityQuestions getTSecurityQuestions() {
		return this.TSecurityQuestions;
	}

	public void setTSecurityQuestions(TSecurityQuestions TSecurityQuestions) {
		this.TSecurityQuestions = TSecurityQuestions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFILE_ID")
	public TProfile getTProfile() {
		return this.TProfile;
	}

	public void setTProfile(TProfile TProfile) {
		this.TProfile = TProfile;
	}

	@Column(name = "ANSWER_DESCR", length = 50)
	public String getAnswerDescr() {
		return this.answerDescr;
	}

	public void setAnswerDescr(String answerDescr) {
		this.answerDescr = answerDescr;
	}

}
