package org.tsn.entity;

// Generated Apr 23, 2015 9:21:54 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TTeam generated by hbm2java
 */
@Entity
@Table(name = "t_team", catalog = "tsn_test")
public class TTeam implements java.io.Serializable
{

	private int			teamId;
	private TLogin		TLogin;
	private TProjects	TProjects;

	public TTeam()
	{
	}

	public TTeam(int teamId)
	{
		this.teamId = teamId;
	}

	public TTeam(int teamId, TLogin TLogin, TProjects TProjects)
	{
		this.teamId = teamId;
		this.TLogin = TLogin;
		this.TProjects = TProjects;
	}

	@Id
	@Column(name = "TEAM_ID", unique = true, nullable = false)
	public int getTeamId()
	{
		return this.teamId;
	}

	public void setTeamId(int teamId)
	{
		this.teamId = teamId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOGIN_ID")
	public TLogin getTLogin()
	{
		return this.TLogin;
	}

	public void setTLogin(TLogin TLogin)
	{
		this.TLogin = TLogin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public TProjects getTProjects()
	{
		return this.TProjects;
	}

	public void setTProjects(TProjects TProjects)
	{
		this.TProjects = TProjects;
	}

}
