package org.tsn.entity;

// Generated Feb 19, 2015 10:13:35 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TTeam generated by hbm2java
 */
@Entity
@Table(name = "t_team")
public class TTeam implements IBaseEntity {

	private static final long serialVersionUID = -3941778168585457341L;
	
	private int teamId;
	private TProjects TProjects;
	private TProfile TProfile;

	public TTeam() {
	}

	public TTeam(int teamId) {
		this.teamId = teamId;
	}

	public TTeam(int teamId, TProjects TProjects, TProfile TProfile) {
		this.teamId = teamId;
		this.TProjects = TProjects;
		this.TProfile = TProfile;
	}

	@Id
	@Column(name = "TEAM_ID", unique = true, nullable = false)
	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public TProjects getTProjects() {
		return this.TProjects;
	}

	public void setTProjects(TProjects TProjects) {
		this.TProjects = TProjects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFILE_ID")
	public TProfile getTProfile() {
		return this.TProfile;
	}

	public void setTProfile(TProfile TProfile) {
		this.TProfile = TProfile;
	}

}
